---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd
  - authentik
  - downloads
  - monitoring
  - rook
  - cnpg
  - external-dns
  - external-secrets
  - cert-manager
  - root
  - kube-system
  - media
  - github-actions
  - velero
  - system-upgrade
  - databases
  - tooling
  - home-automation
  - kubevirt
  - cluster-api
  - game-servers
  - falco
  - projectsveltos
  - hpc
  - git
