---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ess-well-known
spec:
  hostnames:
    - chat.volcan.cloud
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https-volcan
    - name: internal
      namespace: kube-system
      sectionName: https-volcan
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ess-well-known
          port: 8010
