---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db-synapse.yaml
  - db-mas.yaml
  - httproute-synapse.yaml
  - httproute-wellknown.yaml
  - httproute-element.yaml
  - httproute-mas.yaml
  - httproute-admin.yaml
  - httproute-rtc.yaml
