---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: crow
spec:
  hostnames:
    - ci.volcan.cloud
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https-volcan
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: crow
          port: 80
