---
controllers:
  main:
    containers:
      main:
        nameOverride: vaultwarden
        image:
          repository: ghcr.io/dani-garcia/vaultwarden
          tag: 1.35.1
        env:
          DATABASE_URL:
            secretKeyRef:
              name: vaultwarden
              key: DATABASE_URL
service:
  main:
    controller: main
    ports:
      http:
        port: 80
persistence:
  key:
    type: secret
    name: vaultwarden
    advancedMounts:
      main:
        main:
          - path: /data/rsa_key.pem
            readOnly: true
            subPath: rsa_key.pem
route:
  app:
    hostnames:
      - vaultwarden.suslian.engineer
    parentRefs:
      - name: internal
        namespace: kube-system
        sectionName: https
