---
apiVersion: v1
kind: Namespace
metadata:
  name: capk-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: kubevirt
  namespace: capk-system
spec:
  version: v0.11.0
