alloy:
  enabled: false
pyroscope:
  persistence:
    enabled: true
  podAnnotations:
    profiles.grafana.com/cpu.scrape: "false"
    profiles.grafana.com/memory.scrape: "false"
    profiles.grafana.com/goroutine.scrape: "false"
