falco:
  webserver:
    prometheus_metrics_enabled: true
driver:
  kind: modern_ebpf
tty: true
collectors:
  kubernetes:
    enabled: true
metrics:
  enabled: true
serviceMonitor:
  create: true
grafana:
  dashboards:
    enabled: true
    configMaps:
      falco:
        folder: Falco
customRules:
  rules-custom.yaml: |-
    - list: known_drop_and_execute_containers
      items: ['ghcr.io/k8snetworkplumbingwg/multus-cni','docker.io/moby/buildkit', 'docker.io/grafana/alloy']
      override:
        items: append
falcosidekick:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRules:
    enabled: true
  grafana:
    dashboards:
      enabled: true
      configMaps:
        falcosidekick:
          folder: Falco
  config:
    loki:
      hostport: http://loki-headless.monitoring.svc.cluster.local:3100
      grafanaDashboard:
        configMap:
          folder: Falco
