---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "pool"
spec:
  allowFirstLastIPs: "No"
  blocks:
    - start: "10.0.10.2"
      stop: "10.0.10.254"
    - start: "10.0.1.2"
      stop: "10.0.1.254"
